name: Sync-配置檔案
on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 19 * * *"  # Runs every day at 7:00 PM UTC (3:00 AM Taipei time)
  push:
     branches:
       - main
     paths:
       - .github/workflows/sync-up-配置檔案.yml # 僅在此檔案變更時觸發
       - .github/sync-配置檔案.yml              # 僅在此檔案變更時觸發
       - .github/workflows/sync-up-名單清單.yml # 僅在此檔案變更時觸發
       - .github/sync-名單清單.yml              # 僅在此檔案變更時觸發
       - .gitignore                    # 僅在此檔案變更時觸發
       - CountCSVLine.py               # 僅在此檔案變更時觸發
jobs:
  sync-backup-workflow:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4

      - name: Sync up
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.REPO_FILE_SYNC_WENCHIEHLEE }}
          CONFIG_PATH: .github/sync-配置檔案.yml
          COMMIT_EACH_FILE: false
          PR_LABELS: "automated-sync"
          # Uncomment to skip Pull Request and push directly
          SKIP_PR: true
