#.github/workflows/sync-up.yml
name: Sync Common Code
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync-up.yml # 僅在此檔案變更時觸發
      - .github/sync.yml              # 僅在此檔案變更時觸發
jobs:
  sync-backup-workflow:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4

      - name: Sync up
        uses: BetaHuhn/repo-file-sync-action@latest
        with:
          GH_PAT: ${{ secrets.REPO_FILE_SYNC_ACTION_DEPLOYMENTS }}
          CONFIG_PATH: .github/sync.yml
          COMMIT_EACH_FILE: false
          PR_LABELS: "automated-sync"
          # Uncomment to skip Pull Request and push directly
          SKIP_PR: true
